site_name: Entiqon Docs
site_url: https://ialopezg.github.io/entiqon/

theme:
  name: material
  logo: assets/entiqon_black.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

docs_dir: docs-site
use_directory_urls: true

extra:
  base_url: /entiqon

nav:
  - ğŸ  Home: index.md
  - ğŸ“˜ Architecture:
      - Builder Overview: dev/builder/builder_guide.md
      - Infrastructure: documentation-infra.md
  - ğŸ§± Builders:
      - SelectBuilder: dev/builder/select_builder.md
      - InsertBuilder: dev/builder/insert_builder.md
      - UpdateBuilder: dev/builder/update_builder.md
      - DeleteBuilder: dev/builder/delete_builder.md
      - UpsertBuilder: dev/builder/upsert_builder.md
  - ğŸ“¦ Releases:
      - Overview: releases/index.md
      - v1.5.0: releases/release-notes-v1.5.0.md
      - v1.4.0: releases/release-notes-v1.4.0.md
      - v1.3.0: releases/release-notes-v1.3.0.md
      - v1.2.0: releases/release-notes-v1.2.0.md
      - v1.1.0: releases/release-notes-v1.1.0.md
      - v1.0.0: releases/release-notes-v1.0.0.md
      - Full Changelog: CHANGELOG.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - attr_list
  - md_in_html