site_name: Entiqon Docs
site_url: https://ialopezg.github.io/entiqon/

theme:
  name: material
  logo: assets/entiqon_black.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

docs_dir: docs
use_directory_urls: true

extra:
  base_url: /entiqon

nav:
  - ğŸ  Home: index.md

  - ğŸ“¦ Packages:
      - Overview: packages/overview.md
      - Common:
          - Overview: packages/common/overview.md
          - Error: packages/common/error/overview.md
          - Extension:
              - Boolean: packages/common/extension/boolean.md
              - Collection: packages/common/extension/collection.md
              - Date: packages/common/extension/date.md
              - Decimal: packages/common/extension/decimal.md
              - Float: packages/common/extension/float.md
              - Number: packages/common/extension/number.md
              - Object: packages/common/extension/object.md
      - Database: packages/database.md

  - ğŸ“˜ Architecture:
      - Builder Overview: dev/builder/builder_guide.md
      - TokenSystem: docs/dev/build/token.md
      - Infrastructure: documentation-infra.md
      - Dialect: dev/driver/dialect.md
      - Styling: dev/driver/styling.md

  - ğŸ§± Builders:
      - SelectBuilder: dev/builder/select_builder.md
      - InsertBuilder: dev/builder/insert_builder.md
      - UpdateBuilder: dev/builder/update_builder.md
      - DeleteBuilder: dev/builder/delete_builder.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - attr_list
  - md_in_html