site_name: Entiqon Docs
site_url: https://ialopezg.github.io/entiqon/

theme:
  name: material
  logo: assets/entiqon_black.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy

docs_dir: docs-site
use_directory_urls: true

extra:
  base_url: /entiqon

nav:
  - ğŸ  Home: index.md

  - ğŸ“¦ Packages:
      - Overview: packages/overview.md
      - Common: packages/common/overview.md
      - Database: packages/database.md

  - ğŸ“˜ Architecture:
      - Builder Overview: dev/builder/builder_guide.md
      - TokenSystem: docs/dev/build/token.md
      - Infrastructure: documentation-infra.md
      - Dialect: dev/driver/dialect.md
      - Styling: dev/driver/styling.md

  - ğŸ§± Builders:
      - SelectBuilder: dev/builder/select_builder.md
      - InsertBuilder: dev/builder/insert_builder.md
      - UpdateBuilder: dev/builder/update_builder.md
      - DeleteBuilder: dev/builder/delete_builder.md
      - UpsertBuilder: dev/builder/upsert_builder.md

  - ğŸ“¦ Releases:
      - Overview: releases/index.md
      - Lastest: releases/release-notes-v1.10.0.md
      - Full Changelog: CHANGELOG.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - attr_list
  - md_in_html